### ISSUE TITLE
Bump `bare-metal` to 1.0.0

### ISSUE THREAD

**Issue by YuhanLiin** [rust-embedded/msp430#8]
This introduces the Cloneable `CriticalSection` to MSP430. We need to make sure that it's not possible to clone the starting `CriticalSection`s provided by `msp430-rt` into static variables, since that might be unsound. This means that the starting `CriticalSection`s shouldn't have `'static` lifetimes.

**Comment by cr1901** [comment]
>This introduces the Cloneable CriticalSection to MSP430.

Ahhh so, _that's_ where the cloneable `CriticalSection` token came from: https://github.com/rust-embedded/bare-metal/commit/23156b0c5107b7a84bc27f35130094a7833b8d15#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R43

>This means that the starting CriticalSections shouldn't have 'static lifetimes.

A legitimate use of `transmute` :P?

**Comment by YuhanLiin** [comment]
The starting `CriticalSection`s are local variables under the hood, so they already shouldn't be `static`.

**Comment by YuhanLiin** [comment]
It looks like `msp430-rt` needs to be updated with lifetimes constraints as well.

**Comment by cr1901** [comment]
Closed by #9. If there are any issues, follow up PRs and versions can handle them.
